[build]
  # On force la réinstallation de metro et l'alignement des dépendances
  command = "npm install --legacy-peer-deps && npx expo export -p web"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
