[build]
  command = "npm install --legacy-peer-deps && npx expo export"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  EXPO_WEB_DEBUG = "true"
  # Cela aide npm à ignorer les strict peer dependencies dans les environnements CI
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200